import pandas as pd
import matplotlib.pyplot as plt
data = pd.read_csv('soccer_players.csv')
print("Player Data:")
print(data)
top_goals = data.nlargest(5, 'Goals')
print("\nTop 5 Players with the Highest Goals Scored:")
print(top_goals[['Name', 'Goals']])
top_salaries = data.nlargest(5, 'WeeklySalary')
print("\nTop 5 Players with the Highest Salaries:")
print(top_salaries[['Name', 'WeeklySalary']])
average_age = data['Age'].mean()
print("\nAverage Age of Players:", average_age)
above_average_age = data[data['Age'] > average_age]
print("\nPlayers Above Average Age:")
print(above_average_age[['Name', 'Age']])
plt.figure(figsize=(10, 6))
data['Position'].value_counts().plot(kind='bar', color='skyblue')
plt.title('Distribution of Players Based on Positions')
plt.xlabel('Position')
plt.ylabel('Number of Players')
plt.xticks(rotation=45)
plt.grid(axis='y')
plt.show()
